### ISSUE TITLE
PiP is not working 

### ISSUE THREAD

**Issue by loverboy0004** [Neo-Oli/termux-ubuntu#78]
every thing is work perfectly for me but main issue is python-pip is not working 
im on Samsung C5 with Android v9 
-----------------------------see blow----------------------------
root@localhost:/# pip install dryscrape
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
    vendored("colorama")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/__init__.py", line 2, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/initialise.py", line 6, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/ansitowin32.py", line 7, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/winterm.py", line 2, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/win32.py", line 8, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 556, in <module>
    _reset_cache()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 276, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError

root@localhost:/# which python
/usr/bin/python
root@localhost:/# which pip
/usr/bin/pip
-------------------------END-------------------
also try with --no-cache-dir 
also try with python -m pip install dryscrape
also try with pip -v 
also try get_pip.py for update the pip
every time same error comes 
please try to fix it or tell me what i do 

2nd issue is npm not installing packages 
but after all its working amazingly great job guys keep it up

**Comment by dangpzanco** [comment]
Hey, uhm... I recieved an email notification with your username as the sender and I thought it was a spam bot that gmail couldn't catch. So, maybe **change your username**, because other people might not take your messages seriously.

Never mind that, about your problem: it seems like one of those fatal unrecoverable errors pip sometimes makes, like when you try updating pip via `sudo pip install -U pip` (don't try this at home). My advice is to:

### Option 1

**Use Python 3**: Python 2 is retiring in 1 year from now (check the countdown [here](https://pythonclock.org/)) and most libs already support Python 3.

### Option 2

**Reinstall everything**: if you run `sudo apt purge python2`, you'll probably destroy your ubuntu distro. So, try reinstalling EVERYTHING: delete the `ubuntu` folder and rerun the script.

**Comment by utzlol** [comment]
try pypi
